import { motion } from 'framer-motion';

const PrivacyExplainer = () => {
  const steps = [
    {
      title: "Shielded pool with zkSNARKs",
      desc: "Assets sit inside a multi‑asset shielded pool. Zero‑knowledge proofs show that deposits, swaps, and withdrawals are valid without exposing which notes belong to which wallets."
    },
    {
      title: "Backend proving with Rapidsnark",
      desc: "Heavy proofs are generated by a backend prover using Rapidsnark where available, with snarkjs as a fallback. Users see a simple “Swap pending” state instead of watching their browser freeze."
    },
    {
      title: "Chainalysis sanctions screening",
      desc: "Depositors are screened via the Chainalysis API when configured. Phantom keeps on-chain privacy while enforcing entry-point compliance checks."
    },
    {
      title: "Per‑wallet reporting keys",
      desc: "Each wallet can create revocable reporting keys. These keys reveal that wallet’s full history to auditors, lawyers, or tax tools — without breaking global anonymity inside the pool."
    }
  ];

  return (
    <section className="section" id="security">
      <div className="container">
        <div style={{ marginBottom: '4rem' }}>
          <div className="section-label">Cryptographic Stack</div>
          <h2 className="display-lg">
            Privacy first,<br /><em>compliance‑ready</em> when needed.
          </h2>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'minmax(300px, 1fr) minmax(300px, 1fr)', gap: '4rem', alignItems: 'start' }}>

          {/* Left: Step list */}
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            {steps.map((step, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.15, duration: 0.6 }}
                style={{
                  padding: '2.5rem 0',
                  borderTop: idx === 0 ? '1px solid var(--border)' : '1px solid rgba(255,255,255,0.03)',
                  display: 'flex',
                  gap: '2rem'
                }}
              >
                <div style={{ color: 'var(--cyan)', marginTop: '0.2rem' }}>
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                  </svg>
                </div>
                <div>
                  <h3 style={{
                    fontFamily: 'var(--font-display)',
                    fontSize: '1.4rem',
                    fontWeight: 400,
                    marginBottom: '1rem',
                  }}>
                    {step.title}
                  </h3>
                  <p style={{ color: '#fff', fontSize: 'var(--body-size)', fontWeight: 500, lineHeight: 'var(--body-line)' }}>
                    {step.desc}
                  </p>
                </div>
              </motion.div>
            ))}
            <div className="divider" />
          </div>

          {/* Right: Terminal Visual */}
          <motion.div
            initial={{ opacity: 0, scale: 0.98 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.4, duration: 0.8 }}
            className="terminal"
            style={{ position: 'sticky', top: '120px' }}
          >
            <div className="terminal-header">
              <div className="terminal-dot" style={{ background: '#ff5f56' }} />
              <div className="terminal-dot" style={{ background: '#ffbd2e' }} />
              <div className="terminal-dot" style={{ background: '#27c93f' }} />
              <span className="mono t-dim" style={{ marginLeft: '1rem', fontSize: '0.65rem' }}>phantom-node — proof-verifier — live</span>
            </div>
            <div className="terminal-body mono">
              <div style={{ marginBottom: '1.5rem' }}>
                <span className="t-cyan">{">"}</span> Proof job queued <span className="t-white">[swap:0x7f3a...b812]</span><br />
                <span className="t-dim">timestamp : 1709123844</span><br />
                <span className="t-dim">type : DEPOSIT</span><br />
                <span className="t-dim">company_wallet : 0xACME...C0MP</span>
              </div>

              <div style={{ marginBottom: '1.5rem' }}>
                <span className="t-cyan">{">"}</span> Running Groth16 verification (rapidsnark)...<br />
                <span className="t-green">✓ note_exists : valid</span><br />
                <span className="t-green">✓ amount_conservation : valid</span><br />
                <span className="t-green">✓ nullifier_unique : valid</span><br />
                <span className="t-green">✓ ownership_proof : valid</span>
              </div>

              <div style={{ marginBottom: '1.5rem' }}>
                <span className="t-green">✓ Submitting to shielded pool contract</span><br />
                <span className="t-green">✓ Gas paid from user balance (sent to relayer to cover tx)</span>
              </div>

              <div>
                <span className="t-cyan">{">"}</span> Execution complete. Payroll batch sealed.<br />
                <span className="t-green">✓ Reporting key updated for wallet: [0xa1f9...22c6]</span>
              </div>
            </div>
          </motion.div>

        </div>
      </div>

      <style>{`
        @media (max-width: 900px) {
          #security .container > div:last-child {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </section>
  );
};

export default PrivacyExplainer;
